### ISSUE TITLE
Upgrade xml dependency

### ISSUE THREAD

**Issue by rd-martin-jaeger** [AngeloAvv/flutter_flavorizr#103] opened 2022-05-25 14:29 UTC
Can you please upgrade your lib to at least `xml ^6.0.1`

```
Because no versions of flutter_flavorizr match >2.1.3 <3.0.0 and flutter_flavorizr 2.1.3 depends on xml ^5.3.1, flutter_flavorizr ^2.1.3 requires xml ^5.3.1.
And because flutter_svg >=1.1.0 depends on xml ^6.0.1, flutter_flavorizr ^2.1.3 is incompatible with flutter_svg >=1.1.0.
```

**Comment by AngeloAvv** [comment] 2022-05-25 14:34
Duplicate of #13

**Closed by AngeloAvv** 2022-05-25 14:34 UTC
