### ISSUE TITLE
LoadError on ios instructions

### ISSUE THREAD

**Issue by Kleak** [AngeloAvv/flutter_flavorizr#104] opened 2022-06-03 13:06 UTC
I'm trying to generate flavor for my iOS project but i got LoadError on all ios specific instructions

Here my flavorizr part of pubspec.yaml :
```yaml
flavorizr:    
  flavors:
    staging:
      app:
        name: "Staging"
      android:
        applicationId: "my.staging.app"
      ios:
        bundleId: "my.staging.app"
    
    production:
      app: 
        name: "Production"
      android:
        applicationId: "my.prod.app"
      ios:
        bundleId: "my.prod.app"
  
  instructions:
    - android:androidManifest
    - android:buildGradle
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
```

and here an example of the error :
`ruby: No such file or directory -- .tmp/scripts/ios/add_file.rb (LoadError)`

full error for ios:schema
```
Executing task ios:schema
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/create_scheme.rb, ios/Runner.xcodeproj, staging
ruby: No such file or directory -- .tmp/scripts/ios/create_scheme.rb (LoadError)

Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/create_scheme.rb, ios/Runner.xcodeproj, production
ruby: No such file or directory -- .tmp/scripts/ios/create_scheme.rb (LoadError)
```

i have ruby installed
here is the output of `ruby -v`
`ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]`

**Comment by AngeloAvv** [comment] 2022-06-03 15:06
Duplicate of #99

**Closed by AngeloAvv** 2022-06-03 15:06 UTC

**Comment by Kleak** [comment] 2022-06-03 15:14
look like it doesn't fix everything

now i got this 
```
<internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- xcodeproj (LoadError)
        from <internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from .tmp/scripts/ios/add_file.rb:1:in `<main>'
```

but xcodeproj is installed
```
❯ xcodeproj --version
1.21.0
```

**Comment by Kleak** [comment] 2022-06-03 15:18
ok nevermind xcodeproj gem was installed with sudo and my user cannot find it

**Comment by zliebersbach** [comment] 2023-05-01 06:00
Yes, in case anyone is an idiot like me and forgot to install the Xcodeproj **gem**:
```
sudo gem install xcodeproj
```

**Comment by balajiramadoss** [comment] 2023-09-26 17:24
@zliebersbach you're not idiot, you are AWESOME! i fixed it using your solution
