### ISSUE TITLE
E/UIFirst (19112): failed to open /proc/19112/stuck_info, No such file or directory

### ISSUE THREAD

**Issue by HeidenPrasanth** [AngeloAvv/flutter_flavorizr#137] opened 2022-11-04 10:22 UTC
I tried the example project and it also has the issue.
E/UIFirst (19112): failed to open /proc/19112/stuck_info, No such file or directory

**Comment by AngeloAvv** [comment] 2022-11-04 13:18
Duplicate of #136

**Closed** 2022-11-04 13:19 UTC
