### ISSUE TITLE
Handle native string resources per flavour (iOS/Android)

### ISSUE THREAD

**Issue by tenninebt** [AngeloAvv/flutter_flavorizr#69] opened 2021-12-15 16:27 UTC
In many cases you need to define string resources that depends on the flavor. For example, when you use Facebook login, you create a test version of your app which has different ApplicationID, BundleURLSchemes...

For iOS you need to define : CFBundleURLSchemes, FacebookAppID and FacebookDisplayName (Needs to be in [flavor].xcconfig
For iOS you need to define : fb_login_protocol_scheme, facebook_app_id (Needs to be in your build.gradle)

I would be good to be able to define those per flavor for each of the platforms. It could be useful when you don't need something specific like Firebase.

Example :

<pre><code>

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    apple:
      app:
        name: "Apple App"

      android:
        applicationId: "com.example.apple"
        <b>string: "fb_login_protocol_scheme:MyAppURLSchemes-Android-Apple"
        string: "facebook_app_id:MyAppId-Android-Apple"</b>
        firebase:
          config: ".firebase/apple/google-services.json"

      ios:
        bundleId: "com.example.apple"
        <b>string: "CFBundleURLSchemes:MyAppURLSchemes-iOS-Apple"
        string: "FacebookAppID:MyAppId-iOS-Apple"
        string: "FacebookDisplayName:My App - Apple"</b>
        firebase:
          config: ".firebase/apple/GoogleService-Info.plist"

    banana:
      app:
        name: "Banana App"
        
      android:
        applicationId: "com.example.banana"
        <b>string: "fb_login_protocol_scheme:MyAppURLSchemes-Android-Banana"
        string: "facebook_app_id:MyAppId-Android-Banana"</b>
        firebase:
          config: ".firebase/banana/google-services.json"
      ios:
        bundleId: "com.example.banana"
        <b>string: "CFBundleURLSchemes:MyAppURLSchemes-iOS-Banana"
        string: "FacebookAppID:MyAppId-iOS-Banana"
        string: "FacebookDisplayName:My App - Banana"</b>
        firebase:
          config: ".firebase/banana/GoogleService-Info.plist"
</code></pre>

**Comment by AngeloAvv** [comment] 2021-12-21 17:17
Duplicate of #36

**Closed** 2022-01-02 21:34 UTC

**Comment by sharathrajMindstack** [comment] 2022-07-06 17:54
android:
        applicationId: "com.example.apple"
        resValues:
          variable_one:
            type: "string"
            value: "example variable one"
          variable_two:
            type: "string"
            value: "example variable two"


how we can generate resValues without overwriting main_flavor file
