### ISSUE TITLE
[macOS 14.0 & Xcode 15.0]: building the app is failing

### ISSUE THREAD

**Issue by KristijanMitrik** [AngeloAvv/flutter_flavorizr#214] opened 2023-10-05 18:42 UTC
Building the app with the latest macOS and Xcode fails due to the following problem

error: Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-output-files.xcfilelist' (in target 'Runner' from project 'Runner')

Error occurs also in the example app if at least one package is present in the pubspec

**Comment by AngeloAvv** [comment] 2023-10-05 18:44
Duplicate of #145 #96 #17

**Closed by AngeloAvv** 2023-10-05 18:44 UTC

**Comment by SergeShkurko** [comment] 2023-10-19 18:12
@KristijanMitrik i found fix for this problem: https://github.com/AngeloAvv/flutter_flavorizr/issues/217#issuecomment-1771479061
