### ISSUE TITLE
Only on Android

### ISSUE THREAD

**Issue by ramezaniivar** [AngeloAvv/flutter_flavorizr#63] opened 2021-08-07 19:01 UTC
Hi
First of all, thank you very much for your good library

I want to use the library only on Android
please guide me

**Comment by ramezaniivar** [comment] 2021-08-07 19:07
![Untitsled](https://user-images.githubusercontent.com/59112188/128611318-99e8701a-6d4d-406d-b7fd-b4d6485cf601.jpg)

**Comment by AngeloAvv** [comment] 2021-11-14 14:20
Hello @ramezaniivar , you have to use a custom instruction set without including the ios instructions. See [available instructions](https://github.com/AngeloAvv/flutter_flavorizr#available-instructions) for further details.

Duplicate of #45

**Closed by AngeloAvv** 2021-11-14 14:20 UTC

**Comment by Yallan** [comment] 2022-04-05 09:44
Hello @AngeloAvv, i have an Android only flutter project and when i run flutter_flavorizr without iOS instructions, i have this error : 
```
Unhandled exception:
Error reading from ios/Runner/Info.plist. The file does not exist
```
Is it possible to run on an Android only flutter project ?
Thanks

**Comment by AngeloAvv** [comment] 2022-04-05 09:47
Hello @Yallan , can you please attach your flavorizr config?

**Comment by Yallan** [comment] 2022-04-05 09:50
```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    local:
      app:
        name: "Local"
      android:
        applicationId: "com.company.app.local"
        icon: "assets/images/icon-local.png"
      ios:
        bundleId: ""
    preprod:
      app:
        name: "Preprod"
      android:
        applicationId: "com.company.app.preprod"
        icon: "assets/images/icon-preprod.png"
      ios:
        bundleId: ""
    prod:
      app:
        name: "Prod"
      android:
        applicationId: "com.company.app"
        icon: "assets/images/icon-prod.png"
      ios:
        bundleId: ""
  instructions: 
    - android:androidManifest
    - android:buildGradle
    - android:dummyAssets
    - android:icons
    - flutter:flavors
    - flutter:app
    - flutter:targets
```

**Comment by Yallan** [comment] 2022-04-05 09:52
Without the **ios** and **ios: bundleId:** field i have this error :
`The following fields were missing: [ios]. Read the docs for further details`
`The following fields were missing: [bundleId]. Read the docs for further details`

**Comment by Yallan** [comment] 2022-04-05 09:58
It's work when i comment all iOS processors in _initAvailableProcessors()

**Comment by vinceve** [comment] 2022-09-14 09:33
A workaround would be to create an empty Info.plist file under ios/Runner. Seems to work for me
