### ISSUE TITLE
flutter_flavorizr regenerates all the dart files

### ISSUE THREAD

**Issue by imsujan276** [AngeloAvv/flutter_flavorizr#183] opened 2023-06-06 12:22 UTC
I have used the flutter_flavorizr package to generate the prod and dev versions of the app, and it works great. 

But the issue is, every time I run the command `flutter pub run flutter_flavorizr`, it regenerates/adds all the default dart files. The changes in `main.dart` and `flavors.dart` are lost. 

Is there any way to stop regenerating the dart files?

**Comment by AngeloAvv** [comment] 2023-06-07 08:27
Duplicate of #9

**Closed by AngeloAvv** 2023-06-07 08:27 UTC

**Comment by imsujan276** [comment] 2023-06-09 08:58
Seems like this issue is there since 2020.
