### ISSUE TITLE
Auto Generate custom field 

### ISSUE THREAD

**Issue by UffizioHimanshu** [AngeloAvv/flutter_flavorizr#172] opened 2023-05-12 08:31 UTC
Currently flavourizr auto generates title method in flavour.dart file. Is there a way to auto generate other custom defined methods.

**Comment by AngeloAvv** [comment] 2023-06-02 17:36
Duplicate of https://github.com/AngeloAvv/flutter_flavorizr/issues/173

**Closed by AngeloAvv** 2023-06-02 17:36 UTC
