### ISSUE TITLE
Miodified generated dart files being overwritten on command execution

### ISSUE THREAD

**Issue by premedios-i9** [AngeloAvv/flutter_flavorizr#83] opened 2022-02-17 12:39 UTC
If I modify a generated file like "app.dart" and I run the flavorizr command, it will literally replace the file. It should only do this either via:

1. If there is no file named app.dart
2. Through a command line option
3. If the flavour names are different

**Comment by AngeloAvv** [comment] 2022-02-17 13:05
Duplicate of #9

**Closed by AngeloAvv** 2022-02-17 13:05 UTC
